### ISSUE TITLE
feat(main): add default dark mode

### ISSUE THREAD

**Issue by Draika** [byronmejia/isthenewapplewatchout.com#1]
Discord does it so why don't you

**Comment by patrickmccallum** [comment]
+1 but this should default to the dark mode passed by the system first, dark second. Also the dropdown isn't dark until you manually select dark mode. I'll submit this also as a separate issue.

**Comment by byronmejia** [comment]
Issue #22 has solved this by using a proper system theme first. Marking as done for now. Will reopen if new movement occurs.
