### ISSUE TITLE
feat(main): add analytics

### ISSUE THREAD

**Issue by patrickmccallum** [byronmejia/isthenewapplewatchout.com#14]
**Overview**
Add analytics to track visitors to the site

**To Reproduce**
1. Visit website
2. Wonder how much traffic it's getting
3. Remember there's no analytics
4. Wish you'd added analytics earlier

**Recommended Changes**
Add analytics provider to track page views and theme usage

**Screenshots**
N/A

**System Info**
N/A

**Additional context**
Hi Byron

**Comment by byronmejia** [comment]
Already tracking

https://github.com/byronmejia/isthenewapplewatchout.com/blob/master/gatsby-config.js#L33
