### ISSUE TITLE
fix(homepage): pre-order link does not go anywhere

### ISSUE THREAD

**Issue by mark-holmes** [byronmejia/isthenewapplewatchout.com#17]
**Overview**
Clicking the pre-order subtitle does not do anything.

**To Reproduce**
1. Click the pre-order subtitle.
2. Cry

**Recommended Changes**
Pre-order implies that the user can click it in and go to Apple.com and lodge a pre-order. If the intention is to indicate order availability of the Apple Watch, perhaps the copy should be revisited. Maybe growth should be involved in this discussion.

**Screenshots**
![image](https://user-images.githubusercontent.com/6997476/65195531-f88cd300-dac2-11e9-8d15-62d88bdc31b3.png)

**System Info**
All

**Comment by patrickmccallum** [comment]
resolved (kinda) in #23
