### ISSUE TITLE
fix(main): the new apple watch is in fact, out

### ISSUE THREAD

**Issue by byronmejia** [byronmejia/isthenewapplewatchout.com#20]
**Overview**
The apple watch is out now

**To Reproduce**
1. Go to website
2. See how much of a liar the website is

**Recommended Changes**
Change to "Yes"

**System Info**
 - OS: macOS Mojave
 - Browser: Chrome
 - Version: 76

**Additional context**
I've got the new apple watch now

**Comment by patrickmccallum** [comment]
resolved in #23
