### ISSUE TITLE
dark theme extension

### ISSUE THREAD

**Issue by matanui159** [byronmejia/isthenewapplewatchout.com#21]
**Overview**
when dark theme extension light theme not work

**To Reproduce**
1. dark theme extension
2. make light theme
3. no light theme

**Recommended Changes**
magic

**Screenshots**
![image](https://user-images.githubusercontent.com/5038541/65288374-05282e80-db8a-11e9-825c-2cacee2b256d.png)

**System Info**
 - OS: browser
 - Browser: google
 - Version: what is this?????

**Additional context**
be better programming

**Comment by patrickmccallum** [comment]
Banned for racism
