### ISSUE TITLE
chore(main): remove jQuery

### ISSUE THREAD

**Issue by patrickmccallum** [byronmejia/isthenewapplewatchout.com#7]
### Overview
Why the fuck does this website have jQuery

### Steps to repro
1. Visit website
2. Feel like you're back in 2007

### Expected behaviour
1. I should have been forced to write actual JS in the console instead of falling back onto the $

### Recommended changes
1. Get rid of this shit, you're a professional developer

### Screenshot
![image](https://user-images.githubusercontent.com/11825795/65102112-77bfcf80-da0d-11e9-8a45-2816403f33ee.png)

### System info
*OS:* Ubuntu 19.04 Disco Dingo
*Browser:* Google Chrome 76.0.3809.132 (Official Build) (64-bit)

**Comment by byronmejia** [comment]
Thank you for submitting a report. We will try our best to respond with the correct solution when we have a moment. This can take 2-4 business weeks.

**Comment by byronmejia** [comment]
After further investigation, we have found the issue to be the user's browser.

Please see [Chrome Console Utilities](https://developers.google.com/web/tools/chrome-devtools/console/utilities?utm_source=dcc&utm_medium=redirect&utm_campaign=2016q3#selector)
