### ISSUE TITLE
fix(main): on hover theme selector

### ISSUE THREAD

**Issue by braydonburn** [byronmejia/isthenewapplewatchout.com#9]
### Overview
No pointer when hovering the theme selector
 
### Steps to repro
1. Visit website
2. Hover theme selector dropdown

### Recommended changes
1. Make it show a pointer when hovering over selections for better readability

### Screenshot
![image](https://user-images.githubusercontent.com/26685982/65105031-f3724a00-da16-11e9-8301-bce55370fb0b.png)

### System info
_OS:_ Ubuntu 18.04
_Browser:_ Google Chrome 76.0.3809.132 (Official Build) (64-bit)

**Comment by patrickmccallum** [comment]
+1 Probably getting penalised on Google for this one.

**Comment by patrickmccallum** [comment]
Resolved in #11
